config/routes.rb
Rails.application.routes.draw do
  mount LikeDislike::Engine, at: '/'
  resources :likes
  resources :improvements
  resources :contents
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'likes#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/improvement.rb
class Improvement < ApplicationRecord
	validates :content, presence: true
	validates :name, presence: true
	validates :email, presence:true

end

app/models/like.rb
class Like < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def vote
  end
end

app/controllers/improvements_controller.rb
class ImprovementsController < ApplicationController
  before_action :set_improvement, only: [:show, :edit, :update, :destroy]

  # GET /improvements
  # GET /improvements.json
  def index
    @improvements = Improvement.all
  end

  # GET /improvements/1
  # GET /improvements/1.json
  def show
  end

  # GET /improvements/new
  def new
    @improvement = Improvement.new
  end

  # GET /improvements/1/edit
  def edit
  end

  # POST /improvements
  # POST /improvements.json
  def create
    @improvement = Improvement.new(improvement_params)

    respond_to do |format|
      if @improvement.save
        format.html { redirect_to @improvement, notice: 'Thank you! Your advice was successfully submitted.' }
        format.json { render :show, status: :created, location: @improvement }
      else
        format.html { render :new }
        format.json { render json: @improvement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /improvements/1
  # PATCH/PUT /improvements/1.json
  def update
    respond_to do |format|
      if @improvement.update(improvement_params)
        format.html { redirect_to @improvement, notice: 'Advice was successfully updated.' }
        format.json { render :show, status: :ok, location: @improvement }
      else
        format.html { render :edit }
        format.json { render json: @improvement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /improvements/1
  # DELETE /improvements/1.json
  def destroy
    @improvement.destroy
    respond_to do |format|
      format.html { redirect_to improvements_url, notice: 'Advice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_improvement
      @improvement = Improvement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def improvement_params
      params.require(:improvement).permit(:name, :email, :content)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: [:show, :edit, :update, :destroy]

  # GET /likes
  # GET /likes.json
  def index
    @likes = Like.all
  end

  # GET /likes/1
  # GET /likes/1.json
  def show
  end

  # GET /likes/new
  def new
    @like = Like.new
  end

  # GET /likes/1/edit
  def edit
  end

  # POST /likes
  # POST /likes.json
  def create
    @like = Like.new(like_params)

    respond_to do |format|
      if @like.save
        format.html { redirect_to @like, notice: 'Like was successfully created.' }
        format.json { render :show, status: :created, location: @like }
      else
        format.html { render :new }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /likes/1
  # PATCH/PUT /likes/1.json
  def update
    respond_to do |format|
      if @like.update(like_params)
        format.html { redirect_to @like, notice: 'Like was successfully updated.' }
        format.json { render :show, status: :ok, location: @like }
      else
        format.html { render :edit }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1
  # DELETE /likes/1.json
  def destroy
    @like.destroy
    respond_to do |format|
      format.html { redirect_to likes_url, notice: 'Like was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_like
      @like = Like.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def like_params
      params.require(:like).permit(:like)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/improvements_helper.rb
module ImprovementsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/improvements/_form.html.erb
<%= form_for(improvement) do |f| %>
  <% if improvement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(improvement.errors.count, "error") %> prohibited this improvement from being saved:</h2>

      <ul>
      <% improvement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit "Submit"%>
  </div>
<% end %>

app/views/improvements/edit.html.erb
<h1>Editing Improvement</h1>

<%= render 'form', improvement: @improvement %>

<%= link_to 'Show', @improvement %> |
<%= link_to 'Back', improvements_path %>

app/views/improvements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Improvements</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @improvements.each do |improvement| %>
      <tr>
        <td><%= improvement.name %></td>
        <td><%= improvement.email %></td>
        <td><%= improvement.content %></td>
        <td><%= link_to 'Edit', edit_improvement_path(improvement) %></td>
        <td><%= link_to 'Destroy', improvement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p id=test></p>

<%= link_to 'Back', new_like_path %>


<!-- <script> 

document.getElementById("number").innerHTML =  "Your are the " + NumLike + "th person who likes our service";
</script> -->

app/views/improvements/new.html.erb
<h1>Please Give Us Some Advice</h1>

<%= render 'form', improvement: @improvement %>

<%= link_to 'Back', new_like_path %>
<br><br>

<%= link_to 'Show all Advice', improvements_path %>

app/views/improvements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @improvement.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @improvement.email %>
</p>

<p>
  <strong>Content:</strong>
  <%= @improvement.content %>
</p>

<%= link_to 'Edit', edit_improvement_path(@improvement) %> |
<%= link_to 'Back', new_like_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Edmonton</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/_form.html.erb
<%= form_for(like) do |f| %>
  <% if like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
      <% like.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="hidden">
    <%= f.number_field :like %>
  </div>

  <div class="actions">
    <%= f.submit "Like"%>
  </div>
<% end %>

app/views/likes/edit.html.erb
<h1>Editing Like</h1>

<%= render 'form', like: @like %>

<%= link_to 'Show', @like %> |
<%= link_to 'Back', likes_path %>

app/views/likes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Likes</h1>

<table>
  <thead>
    <tr>
      <th>Like</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @likes.each do |like| %>
      <tr>
        <td><%= like.like %></td>
        <td><%= link_to 'Destroy', like, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>

  </tbody>

  </table>


<% @likes.each do |like| %>

  <%= like.id %>
  <% end %>





<br>


<br>
<br>

<%= link_to 'New Like', new_like_path %>

app/views/likes/new.html.erb
<!DOCTYPE html>
<html>

<body>

<h1>Please Give Us Some Feedback</h1>
<p>Do you like our service?</p>

<%= render 'form', like: @like %>

<a href="/improvements/new"> Need Improve</a>
</body>

</html>

app/views/likes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Thank you!</strong>
  <div>
  <%= @like.like%>
  </div>

</p>


<p id='number'></p>


<%= link_to 'Back', new_like_path %>


<script> 
	window.location.href 
	
var url = document.URL;
var array = url.split('/');
var NumLike = array[array.length-1];

document.getElementById("number").innerHTML =  "Your are the " + NumLike + "th person who likes our service";
</script>

app/views/likes/vote.html.erb
<!DOCTYPE html>
<html>
<head>

</head>
<body>

<h1>Please Give Us Some Feedback</h1>
<p>This is a paragraph.</p>
<%= form_for(like) do |f| %>
	<div class="actions">
		<%= f.submit %>	
    </div>
<% end %>

</body>

</html>